import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ConsentProvider } from "@/lib/consent";
import { ConsentGate } from "@/components/ConsentGate";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ── Canonical base for all absolute URLs (og:image, sitemap, etc.) ────────────
const BASE_URL = "https://pluggers.it";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  // ── Title template ──────────────────────────────────────────────────────────
  title: {
    default: "Pluggers — Il professionista giusto, al momento giusto.",
    template: "%s — Pluggers",
  },

  // ── Primary meta ───────────────────────────────────────────────────────────
  description:
    "Trova idraulici, elettricisti, muratori e altri artigiani qualificati vicino a te. " +
    "Pluggers mette in contatto chi ha un problema con chi ha la soluzione.",

  keywords: [
    "pluggers",
    "trovare artigiani",
    "professionisti per la casa",
    "idraulico vicino a me",
    "elettricista veloce",
    "muratore qualificato",
    "artigiani di fiducia",
    "manutenzione casa",
    "lavori edili",
  ],

  authors: [{ name: "Pluggers", url: BASE_URL }],
  creator: "Pluggers",
  publisher: "Pluggers",

  // ── Open Graph (WhatsApp, Facebook, LinkedIn, Telegram) ────────────────────
  openGraph: {
    type: "website",
    locale: "it_IT",
    url: BASE_URL,
    siteName: "Pluggers",
    title: "Pluggers — Il professionista giusto, al momento giusto.",
    description:
      "L'applicazione che mette in contatto chi ha un problema con chi ha la soluzione. " +
      "Idraulici, elettricisti, muratori e molto altro.",
    images: [
      {
        url: "/og-image",          // generated by app/opengraph-image.tsx
        width: 1200,
        height: 630,
        alt: "Pluggers — Trova professionisti qualificati nella tua zona",
      },
    ],
  },

  // ── Twitter / X ────────────────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: "Pluggers — Il professionista giusto, al momento giusto.",
    description:
      "Trova idraulici, elettricisti e altri artigiani qualificati vicino a te.",
    images: ["/og-image"],
  },

  // ── Robots (global default — pages override when needed) ───────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" suppressHydrationWarning>
      <body className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}>
        <ConsentProvider>
          <ThemeProvider>{children}</ThemeProvider>
          <ConsentGate />
        </ConsentProvider>
      </body>
    </html>
  );
}
