import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ConsentProvider } from "@/lib/consent";
import { ConsentGate } from "@/components/ConsentGate";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  display: "swap",
});

// ── Canonical base for all absolute URLs (og:image, sitemap, etc.) ────────────
const BASE_URL = "https://www.plggrs.it";

const DESCRIPTION =
  "Racconta il problema con testo e foto: Pluggers capisce di che si tratta e ti collega " +
  "ai professionisti della tua zona. Costo Chiamata indicato prima della visita, chat e preventivo in app.";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  // ── Title template ──────────────────────────────────────────────────────────
  title: {
    default: "Pluggers — Il professionista giusto, al momento giusto.",
    template: "%s — Pluggers",
  },

  // ── Primary meta ───────────────────────────────────────────────────────────
  description: DESCRIPTION,

  keywords: [
    "pluggers",
    "trovare artigiani",
    "professionisti per la casa",
    "idraulico vicino a me",
    "elettricista veloce",
    "muratore qualificato",
    "artigiani di fiducia",
    "manutenzione casa",
    "lavori edili",
  ],

  authors: [{ name: "Pluggers", url: BASE_URL }],
  creator: "Pluggers",
  publisher: "Pluggers",

  // ── Open Graph (WhatsApp, Facebook, LinkedIn, Telegram) ────────────────────
  openGraph: {
    type: "website",
    locale: "it_IT",
    url: BASE_URL,
    siteName: "Pluggers",
    title: "Pluggers — Il professionista giusto, al momento giusto.",
    description: DESCRIPTION,
    images: [
      {
        url: "/og-image",          // generated by app/opengraph-image.tsx
        width: 1200,
        height: 630,
        alt: "Pluggers — Trova professionisti qualificati nella tua zona",
      },
    ],
  },

  // ── Twitter / X ────────────────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: "Pluggers — Il professionista giusto, al momento giusto.",
    description:
      "Racconta il problema: Pluggers capisce di che si tratta e ti collega ai professionisti vicini.",
    images: ["/og-image"],
  },

  // ── Robots (global default — pages override when needed) ───────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" suppressHydrationWarning>
      <body className={`${jakarta.variable} font-sans antialiased`}>
        <ConsentProvider>
          <ThemeProvider>{children}</ThemeProvider>
          <ConsentGate />
        </ConsentProvider>
      </body>
    </html>
  );
}
