import type { Metadata } from "next";
import { APP_STORE_URL, PLAY_STORE_URL, WEB_APP_URL } from "@/components/landing/links";
import { ORG, SITE_URL, SOCIAL_LINKS } from "@/lib/site";

// ── Page metadata ────────────────────────────────────────────────────────────

/** Generated by app/opengraph-image.tsx. */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Pluggers — Il professionista giusto, al momento giusto.",
};

type PageMeta = {
  /** Shown as "<title> — Pluggers" unless `absolute`. Keep the result within 60 characters. */
  title: string;
  /** 140–160 characters. */
  description: string;
  /** Path from the site root; canonical and og:url resolve against `metadataBase`. */
  path: string;
  absolute?: boolean;
  publishedTime?: string;
};

export function pageMetadata({ title, description, path, absolute, publishedTime }: PageMeta): Metadata {
  const fullTitle = absolute ? title : `${title} — ${ORG.name}`;
  const shared = {
    locale: "it_IT",
    siteName: ORG.name,
    url: path,
    title: fullTitle,
    description,
    images: [OG_IMAGE],
  };
  return {
    title: absolute ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: publishedTime
      ? { ...shared, type: "article", publishedTime }
      : { ...shared, type: "website" },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

// ── Structured data (schema.org) ────────────────────────────────────────────

export const ORG_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;
const TORINO = { "@type": "City", name: "Torino" };

export function graph(...nodes: object[]) {
  return { "@context": "https://schema.org", "@graph": nodes };
}

export const organizationSchema = {
  "@type": "Organization",
  "@id": ORG_ID,
  name: ORG.name,
  legalName: ORG.legalName,
  // plggrs.it is the domain; people search the name, sometimes spelled like the domain
  alternateName: ["Plggrs", "Pluggers app"],
  vatID: `IT${ORG.vatNumber}`,
  taxID: ORG.vatNumber,
  url: SITE_URL,
  logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.png` },
  description: ORG.summary,
  email: ORG.email,
  foundingDate: ORG.foundingDate,
  address: {
    "@type": "PostalAddress",
    streetAddress: ORG.address.street,
    postalCode: ORG.address.postalCode,
    addressLocality: ORG.address.city,
    addressRegion: ORG.address.region,
    addressCountry: ORG.address.country,
  },
  areaServed: TORINO,
  sameAs: SOCIAL_LINKS.map((s) => s.href),
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: ORG.email,
    url: `${SITE_URL}/supporto`,
    availableLanguage: "it",
  },
};

export const websiteSchema = {
  "@type": "WebSite",
  "@id": WEBSITE_ID,
  url: SITE_URL,
  name: ORG.name,
  description: ORG.summary,
  inLanguage: "it-IT",
  publisher: { "@id": ORG_ID },
};

const storeUrls = [APP_STORE_URL, PLAY_STORE_URL].filter(Boolean);

// Until the store links exist, declare only the platform people can open today: the web version.
export const appSchema = {
  "@type": storeUrls.length > 0 ? "MobileApplication" : "WebApplication",
  "@id": `${SITE_URL}/#app`,
  name: ORG.name,
  description: ORG.summary,
  url: WEB_APP_URL,
  operatingSystem: storeUrls.length > 0 ? "iOS, Android, Web" : "Web",
  applicationCategory: "LifestyleApplication",
  inLanguage: "it",
  offers: { "@type": "Offer", price: "0", priceCurrency: "EUR" },
  publisher: { "@id": ORG_ID },
  ...(storeUrls.length > 0 && { downloadUrl: storeUrls }),
};

export function serviceSchema({ name, serviceType, description, path }: {
  name: string;
  serviceType: string;
  description: string;
  path: string;
}) {
  return {
    "@type": "Service",
    "@id": `${SITE_URL}${path}#service`,
    name,
    serviceType,
    description,
    url: `${SITE_URL}${path === "/" ? "" : path}`,
    areaServed: TORINO,
    // Pluggers connects people with the professionals who do the work: it brokers, it doesn't provide
    broker: { "@id": ORG_ID },
  };
}

/** The page node that ties breadcrumb and main entity to the WebSite. */
export function pageSchema({ path, name, type = "WebPage", mainEntity }: {
  path: string;
  name: string;
  type?: "WebPage" | "CollectionPage" | "AboutPage" | "ContactPage";
  mainEntity?: string;
}) {
  const url = `${SITE_URL}${path === "/" ? "" : path}`;
  return {
    "@type": type,
    "@id": `${url}#webpage`,
    url,
    name,
    inLanguage: "it-IT",
    isPartOf: { "@id": WEBSITE_ID },
    ...(path !== "/" && { breadcrumb: { "@id": `${url}#breadcrumb` } }),
    ...(mainEntity && { mainEntity: { "@id": mainEntity } }),
  };
}

export function faqSchema(items: readonly { q: string; a: string }[]) {
  return {
    "@type": "FAQPage",
    mainEntity: items.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };
}

/** Pass the trail without the home page; it is added first. */
export function breadcrumbSchema(trail: { name: string; path: string }[]) {
  const last = trail.at(-1)?.path ?? "/";
  return {
    "@type": "BreadcrumbList",
    "@id": `${SITE_URL}${last === "/" ? "" : last}#breadcrumb`,
    itemListElement: [{ name: "Home", path: "/" }, ...trail].map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: `${SITE_URL}${item.path === "/" ? "" : item.path}`,
    })),
  };
}
